package objects;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "REPLACED_BY_VALUE_IN_PROPERTIES_FILE")
public class TrackInfo extends DataBaseObject {
	
	private String id;
	private double pathLength;
	private double timeStopped; 
	private double noStops; 
	private double timeSpent; 
	private double inactiveTime; 
	private double sThetaChange; 
	private double sThetaIn; 
	private double sThetaOut; 
	private double sThetaInOut;
	private double timePerStop;
	private double totAvrgSpeed;
	private double timesStoppedHere;
	private double x1;
	private double y1;
	private double x2;
	private double y2;
	private int characteristic;
	
	@DynamoDBAttribute (attributeName = "Characteristic")
	public int getCharacteristic() {
		return characteristic;
	}
	public void setCharacteristic(int characteristic) {
		this.characteristic = characteristic;
	}
	
    @DynamoDBHashKey(attributeName = "ID")
    @DynamoDBAutoGeneratedKey
    public String getId() { return id; }
    public void setId(String ID) { this.id = ID; } 

	@DynamoDBIndexHashKey(attributeName= "Phone_ID", globalSecondaryIndexName="Phone_Index")
	public String getPHONE_ID() {
		return phone_id;
	}
	public void setPHONE_ID(String phone_id){
		this.phone_id = phone_id;
	}
	
	@DynamoDBAttribute (attributeName = "TIMES_STOPPED_HERE")
	public double getTIMESSTOPPEDHERE() {
		return timesStoppedHere;
	}
	public void setTIMESSTOPPEDHERE(double timesStoppedHere){
		this.timesStoppedHere = timesStoppedHere;
	}
	
	
	@DynamoDBAttribute (attributeName = "TOTAL_AVRG_SPEED")
	public double getTOTAVRGSPEED() {
		return totAvrgSpeed;
	}	
	public void setTOTAVRGSPEED(double totAvrgSpeed){
		this.totAvrgSpeed = totAvrgSpeed;
	}
	
	
	@DynamoDBAttribute (attributeName = "TIME_PER_STOP")
	public double getTIMEPERSTOP() {
		return timePerStop;
	}
	public void setTIMEPERSTOP(double timePerStop){
		this.timePerStop = timePerStop;
	}
	
	
	@DynamoDBIndexRangeKey(attributeName = "Track_no" , globalSecondaryIndexName="Phone_Index")
	public int getTRACK_NO() {
		return track_no;
	}
	public void setTRACK_NO(int track_no) {
		this.track_no = track_no;
	}
	
	@DynamoDBAttribute (attributeName = "X1")
	public double getX1() {
		return x1;
	}
	public void setX1(double x1) {
		this.x1 = x1;
	}
	
	@DynamoDBAttribute (attributeName = "Y1")
	public double getY1() {
		return y1;
	}
	public void setY1(double y1) {
		this.y1 = y1;
	}
	
	@DynamoDBAttribute (attributeName = "X2")
	public double getX2() {
		return x2;
	}
	public void setX2(double x2) {
		this.x2 = x2;
	}
	
	@DynamoDBAttribute (attributeName = "Y2")
	public double getY2() {
		return y2;
	}
	public void setY2(double y2) {
		this.y2 = y2;
	}
	
	@DynamoDBAttribute (attributeName = "PATH_LENGTH")
	public double getPATH_LENGTH() {
		return pathLength;
	}
	public void setPATH_LENGTH(double pathLength) {
		this.pathLength = pathLength;
	}
	
	@DynamoDBAttribute (attributeName = "TIME_STOPPED")
	public double getTIME_STOPPED() {
		return timeStopped;
	}
	public void setTIME_STOPPED(double timeStopped) {
		this.timeStopped = timeStopped;
	}
	
	@DynamoDBAttribute (attributeName = "NO_STOPS")
	public double getNO_STOPS() {
		return noStops;
	}
	public void setNO_STOPS(double noStops) {
		this.noStops = noStops;
	}
	
	@DynamoDBAttribute (attributeName = "TIME_SPENT")
	public double getTIME_SPENT() {
		return timeSpent;
	}
	public void setTIME_SPENT(double timeSpent) {
		this.timeSpent = timeSpent;
	}
	
	@DynamoDBAttribute (attributeName = "INACTIVE_TIME")
	public double getINACTIVE_TIME() {
		return inactiveTime;
	}
	public void setINACTIVE_TIME(double inactiveTime) {
		this.inactiveTime = inactiveTime;
	}
	
	@DynamoDBAttribute (attributeName = "S_THETA_CHANGE")
	public double getSTHETACHANGE() {
		return sThetaChange;
	}
	public void setSTHETACHANGE(double sThetaChange) {
		this.sThetaChange = sThetaChange;
	}
	
	@DynamoDBAttribute (attributeName = "S_THETA_IN")
	public double getSTHETAIN() {
		return sThetaIn;
	}
	public void setSTHETAIN(double sThetaIn) {
		this.sThetaIn = sThetaIn;
	}
	
	@DynamoDBAttribute (attributeName = "S_THETA_OUT")
	public double getSTHETAOUT() {
		return sThetaOut;
	}
	public void setSTHETAOUT(double sThetaOut) {
		this.sThetaOut = sThetaOut;
	}
	
	@DynamoDBAttribute (attributeName = "S_THETA_IN_OUT")
	public double getSTHETAINOUT() {
		return sThetaInOut;
	}
	public void setSTHETAINOUT(double sThetaInOut) {
		this.sThetaInOut = sThetaInOut;
	}
	@Override
	public String toString() {
		return "TrackInfo [PATH_LENGTH=" + pathLength + ", TIME_STOPPED="
				+ timeStopped + ", NO_STOPS=" + noStops + ", TIME_SPENT="
				+ timeSpent + ", INACTIVE_TIME=" + inactiveTime
				+ ", STHETACHANGE=" + sThetaChange + ", STHETAIN=" + sThetaIn
				+ ", STHETAOUT=" + sThetaOut + ", STHETAINOUT=" + sThetaInOut
				+ ", TIMEPERSTOP=" + timePerStop + ", TOTAVRGSPEED="
				+ totAvrgSpeed + ", TIMESSTOPPEDHERE=" + timesStoppedHere
				+ ", X1=" + x1 + ", Y1=" + y1 + ", X2=" + x2 + ", Y2=" + y2
				+ ", PHONE_ID=" + phone_id + ", TRACK_NO=" + track_no + "]";
	}
	
	public String toCSV() {
		return phone_id + "," + track_no + "," + pathLength + ","
				+ timeStopped + "," + noStops + ","
				+ timeSpent + "," + inactiveTime
				+ "," + sThetaChange + "," + sThetaIn
				+ "," + sThetaOut + "," + sThetaInOut
				+ "," + timePerStop + ","
				+ totAvrgSpeed + "," + timesStoppedHere
				+ "," + x1 + "," + y1 + "," + x2 + "," + y2
				 ;
	}
	
	public String toCSVNoRef() {
		return 	pathLength + ","
				+ timeStopped + "," + noStops + ","
				+ timeSpent + "," + inactiveTime
				+ "," + sThetaChange + "," + sThetaIn
				+ "," + sThetaOut + "," + sThetaInOut
				+ "," + timePerStop + ","
				+ totAvrgSpeed + "," + timesStoppedHere
				+ "," + x1 + "," + y1 + "," + x2 + "," + y2
				 ;
	}
	
	public String toCSVNoXY() {
		return phone_id + "," + track_no + "," + pathLength + ","
				+ timeStopped + "," + noStops + ","
				+ timeSpent + "," + inactiveTime
				+ "," + sThetaChange + "," + sThetaIn
				+ "," + sThetaOut + "," + sThetaInOut
				+ "," + timePerStop + ","
				+ totAvrgSpeed + "," + timesStoppedHere;
	}
	
	public String toCSVNoXYNoRef() {
		return pathLength + ","
				+ timeStopped + "," + noStops + ","
				+ timeSpent + "," + inactiveTime
				+ "," + sThetaChange + "," + sThetaIn
				+ "," + sThetaOut + "," + sThetaInOut
				+ "," + timePerStop + ","
				+ totAvrgSpeed + "," + timesStoppedHere;
	}
	
	

}
