package objects;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "REPLACED_BY_VALUE_IN_PROPERTIES_FILE")
public class TrackInfo extends DataBaseObject {
	
	private String ID;
	private double PATH_LENGTH;
	private double TIME_STOPPED; 
	private double NO_STOPS; 
	private double TIME_SPENT; 
	private double INACTIVE_TIME; 
	private double STHETACHANGE; 
	private double STHETAIN; 
	private double STHETAOUT; 
	private double STHETAINOUT;
	private double TIMEPERSTOP;
	private double TOTAVRGSPEED;
	private double TIMESSTOPPEDHERE;
	private double X1;
	private double Y1;
	private double X2;
	private double Y2;
	private int Characteristic;
	
	@DynamoDBAttribute (attributeName = "Characteristic")
	public int getCharacteristic() {
		return Characteristic;
	}
	public void setCharacteristic(int characteristic) {
		Characteristic = characteristic;
	}
	
    @DynamoDBHashKey(attributeName = "ID")
    @DynamoDBAutoGeneratedKey
    public String getId() { return ID; }
    public void setId(String ID) { this.ID = ID; } 

	@DynamoDBIndexHashKey(attributeName= "Phone_ID", globalSecondaryIndexName="Phone_Index")
	public String getPHONE_ID() {
		return PHONE_ID;
	}
	public void setPHONE_ID(String phone_id){
		this.PHONE_ID = phone_id;
	}
	
	@DynamoDBAttribute (attributeName = "TIMES_STOPPED_HERE")
	public double getTIMESSTOPPEDHERE() {
		return TIMESSTOPPEDHERE;
	}
	public void setTIMESSTOPPEDHERE(double tIMESSTOPPEDHERE){
		TIMESSTOPPEDHERE = tIMESSTOPPEDHERE;
	}
	
	
	@DynamoDBAttribute (attributeName = "TOTAL_AVRG_SPEED")
	public double getTOTAVRGSPEED() {
		return TOTAVRGSPEED;
	}	
	public void setTOTAVRGSPEED(double tOTAVRGSPEED){
		TOTAVRGSPEED = tOTAVRGSPEED;
	}
	
	
	@DynamoDBAttribute (attributeName = "TIME_PER_STOP")
	public double getTIMEPERSTOP() {
		return TIMEPERSTOP;
	}
	public void setTIMEPERSTOP(double tIMEPERSTOP){
		TIMEPERSTOP = tIMEPERSTOP;
	}
	
	
	@DynamoDBIndexRangeKey(attributeName = "Track_no" , globalSecondaryIndexName="Phone_Index")
	public int getTRACK_NO() {
		return TRACK_NO;
	}
	public void setTRACK_NO(int tRACK_NO) {
		TRACK_NO = tRACK_NO;
	}
	
	@DynamoDBAttribute (attributeName = "X1")
	public double getX1() {
		return X1;
	}
	public void setX1(double x1) {
		X1 = x1;
	}
	
	@DynamoDBAttribute (attributeName = "Y1")
	public double getY1() {
		return Y1;
	}
	public void setY1(double y1) {
		Y1 = y1;
	}
	
	@DynamoDBAttribute (attributeName = "X2")
	public double getX2() {
		return X2;
	}
	public void setX2(double x2) {
		X2 = x2;
	}
	
	@DynamoDBAttribute (attributeName = "Y2")
	public double getY2() {
		return Y2;
	}
	public void setY2(double y2) {
		Y2 = y2;
	}
	
	@DynamoDBAttribute (attributeName = "PATH_LENGTH")
	public double getPATH_LENGTH() {
		return PATH_LENGTH;
	}
	public void setPATH_LENGTH(double pATH_LENGTH) {
		PATH_LENGTH = pATH_LENGTH;
	}
	
	@DynamoDBAttribute (attributeName = "TIME_STOPPED")
	public double getTIME_STOPPED() {
		return TIME_STOPPED;
	}
	public void setTIME_STOPPED(double tIME_STOPPED) {
		TIME_STOPPED = tIME_STOPPED;
	}
	
	@DynamoDBAttribute (attributeName = "NO_STOPS")
	public double getNO_STOPS() {
		return NO_STOPS;
	}
	public void setNO_STOPS(double nO_STOPS) {
		NO_STOPS = nO_STOPS;
	}
	
	@DynamoDBAttribute (attributeName = "TIME_SPENT")
	public double getTIME_SPENT() {
		return TIME_SPENT;
	}
	public void setTIME_SPENT(double tIME_SPENT) {
		TIME_SPENT = tIME_SPENT;
	}
	
	@DynamoDBAttribute (attributeName = "INACTIVE_TIME")
	public double getINACTIVE_TIME() {
		return INACTIVE_TIME;
	}
	public void setINACTIVE_TIME(double iNACTIVE_TIME) {
		INACTIVE_TIME = iNACTIVE_TIME;
	}
	
	@DynamoDBAttribute (attributeName = "S_THETA_CHANGE")
	public double getSTHETACHANGE() {
		return STHETACHANGE;
	}
	public void setSTHETACHANGE(double sTHETACHANGE) {
		STHETACHANGE = sTHETACHANGE;
	}
	
	@DynamoDBAttribute (attributeName = "S_THETA_IN")
	public double getSTHETAIN() {
		return STHETAIN;
	}
	public void setSTHETAIN(double sTHETAIN) {
		STHETAIN = sTHETAIN;
	}
	
	@DynamoDBAttribute (attributeName = "S_THETA_OUT")
	public double getSTHETAOUT() {
		return STHETAOUT;
	}
	public void setSTHETAOUT(double sTHETAOUT) {
		STHETAOUT = sTHETAOUT;
	}
	
	@DynamoDBAttribute (attributeName = "S_THETA_IN_OUT")
	public double getSTHETAINOUT() {
		return STHETAINOUT;
	}
	public void setSTHETAINOUT(double sTHETAINOUT) {
		STHETAINOUT = sTHETAINOUT;
	}
	@Override
	public String toString() {
		return "TrackInfo [PATH_LENGTH=" + PATH_LENGTH + ", TIME_STOPPED="
				+ TIME_STOPPED + ", NO_STOPS=" + NO_STOPS + ", TIME_SPENT="
				+ TIME_SPENT + ", INACTIVE_TIME=" + INACTIVE_TIME
				+ ", STHETACHANGE=" + STHETACHANGE + ", STHETAIN=" + STHETAIN
				+ ", STHETAOUT=" + STHETAOUT + ", STHETAINOUT=" + STHETAINOUT
				+ ", TIMEPERSTOP=" + TIMEPERSTOP + ", TOTAVRGSPEED="
				+ TOTAVRGSPEED + ", TIMESSTOPPEDHERE=" + TIMESSTOPPEDHERE
				+ ", X1=" + X1 + ", Y1=" + Y1 + ", X2=" + X2 + ", Y2=" + Y2
				+ ", PHONE_ID=" + PHONE_ID + ", TRACK_NO=" + TRACK_NO + "]";
	}
	
	public String toCSV() {
		return PHONE_ID + "," + TRACK_NO + "," + PATH_LENGTH + ","
				+ TIME_STOPPED + "," + NO_STOPS + ","
				+ TIME_SPENT + "," + INACTIVE_TIME
				+ "," + STHETACHANGE + "," + STHETAIN
				+ "," + STHETAOUT + "," + STHETAINOUT
				+ "," + TIMEPERSTOP + ","
				+ TOTAVRGSPEED + "," + TIMESSTOPPEDHERE
				+ "," + X1 + "," + Y1 + "," + X2 + "," + Y2 + "\n"
				 ;
	}
	
	

}
